name: TESTING

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET 
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x'
            - run: dotnet --version
            # - run: dotnet build ./src/flightManager.sln
            - run: dotnet test ./FlightSimulator.sln